[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15" }

error = { path = "../error" }
input = { path = "../input" }
ui_macros = { path = "../ui_macros" }
